### ISSUE TITLE
Not working with 23.04 (Lunar Lobster)?

### ISSUE THREAD

**Issue by tommythorn** [openXC7/toolchain-installer#1]
This might be a red herring, but I have two host:
- skylake running Ubuntu 22.04.2 (Jammy Jellyfish)
- zen3 running Ubuntu 23.04 (Lunar Lobster)

I installed openXC7 on both and it seems to work perfectly on skylake, building blinky in 13s.  However on zen3 everything after Yosys is extremely slow ending in failure:
```
Time spent: 56% 27x read_verilog (1 sec), 7% 13x design (0 sec), ...
Exporting tile and site type data...
Exporting nodes...
Exporting tile and site instances...
bbasm -l xc7k325tffg676-1.bba ../chipdb/xc7k325tffg676-1.bin
make: bbasm: No such file or directory
make: *** [Makefile:18: ../chipdb/xc7k325tffg676-1.bin] Error 127
```
Is this known to work/not-work with Lunar Lobster?

ADD: if I run bbasm manually, it crashes:
```
$ /snap/bin/bbasm -l xc7k325tffg676-1.bba ../chipdb/xc7k325tffg676-1.bin
bbasm: /root/parts/nextpnr-xilinx/src/bba/main.cc:144: int main(int, char**): Assertion `fileOut != nullptr' failed.
Aborted (core dumped)
```

**Comment by tommythorn** [comment]
Sorry, definitely an unrelated problem.

**Comment by hansfbaier** [comment]
Have you created the alias for bbasm? (Install script does that)

**Comment by hansfbaier** [comment]
So can we close this ticket then?

**Comment by tommythorn** [comment]
I thought I closed it already.  I upgraded skylake to 23.10 and it was fine so clearly it's an unrelated issue, sorry about the noise.
