### ISSUE TITLE
Installation fails because of wrong branch version tag

### ISSUE THREAD

**Issue by galloj** [openXC7/toolchain-installer#2]
Right now the openXC7-snap branch has "0.6.0" tag instead of "v0.6.0", which causes the installation to fail. I see this was fixed recently by this commit d6365f9a4607aa3452697f71eae39fb638070e1b, but then it was changed back by this one b0da81c84e926a932106745d572bfc2e79493a9c. I am not sure if the correct fix is to remove the "v" prefix from the code or add it to the tag, so I am just creating issue and not PR.

**Comment by hansfbaier** [comment]
Thanks for reporting! Fixed.
